version: "3"

services:
  postgres:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    env_file:
      - packages/env/.env
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: unless-stopped
